# Site settings
title: 若林研究室
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  筑波大学 情報学群 知識情報・図書館学類 知識情報システム主専攻
  若林研究室のホームページです．
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  wkblab

# Build settings
markdown: kramdown
exclude: ["vendor", "Gemfile", "Gemfile.lock"]
