title: マルチエージェント学習・言語理解研究室（若林研究室）（旧・機械学習・言語理解研究室）
description: > # this means to ignore newlines until "baseurl:"
  筑波大学 図書館情報メディア系 マルチエージェント学習・言語理解研究室（若林研究室）（旧・機械学習・言語理解研究室）のホームページです．
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site you most probably don't need to set it
author: ""
github_username: tezuka-wakabayashi-lab

# Build settings
markdown: kramdown
theme: minima
masthead: /assets/masthead.jpg
paginate: 30 # pagination based on number of posts
paginate_path: "page/:num"
plugins: [jekyll-feed, jekyll-paginate]

masthead: /assets/masthead.jpg
show_excerpts: true

exclude: [Gemfile, Gemfile.lock, vendor]
